### ISSUE TITLE
Lua migrated to nelua

### ISSUE THREAD

**Issue by jujubeja** [Limit-Theory-Redux/ltheory#286]
https://github.com/edubart/nelua-benchmarks Benchmarks for comparing efficiency of [nelua](https://github.com/edubart/nelua-lang) with Lua, LuaJIT and C

nelua Overall better performance than Lua LuaJIT

**Comment by dgavedissian** [comment]
nelua certainly looks interesting. However, it's not as simple as simply substituting LuaJIT for nelua, because nelua is ultimately a Lua to C transpiler and is still quite immature and doesn't support some crucial features such as:

* Tables
* Dynamic typing (all variables are statically typed once inferred)

Plus, we lose some of the flexibility benefits of a JIT compiled scripting language such as dynamic reloading.

We utilise LuaJIT's FFI library extensively to bind to the LuaJIT bytecode compiler as efficiently as possible, so the Lua part of our codebase is not specifically the bottleneck right now.

I'm going to go ahead and close this issue as a result.
