### ISSUE TITLE
Limit-Theory-Redux networking

### ISSUE THREAD

**Issue by jujubeja** [Limit-Theory-Redux/ltheory#287]
https://medium.com/1kxnetwork/autonomous-worlds-the-case-for-fully-on-chain-games-3066db695a5a Autonomous Worlds: The Case for Fully On-chain Games

**Comment by dgavedissian** [comment]
This issue is not actionable, because (a) we don't have any plans for multiplayer and (b) on-chain "metaverse" benefits such as in-game items, skins, etc are far beyond the scope of what we're planning to work on.

(note: I used to work for Improbable, which is very much in the business of Autonomous Worlds, so I'm fairly familiar with the topic :))
